# recipes
# User
USERNAME_MAX_LENGTH = 150
USERNAME_VALIDATOR_REGEX = r'^[\w.@+-]+$'
FNAME_MAX_LENGTH = 150
LNAME_MAX_LENGTH = 150

# Ingredient
INGREDIENT_MAX_NAME = 128
INGREDIENT_MAX_MU = 64

# Recipe
RECIPE_MAX_NAME = 256
RECIPE_COOKING_TIME_LIMIT_VALUE = 1

# IngredientInRecipe
ING_IN_REC_AMOUNT_LIMIT_VALUE = 1

# populate_ingredients
DATA_COPY_PATH = 'data_copy'
